name: Bump version to next SNAPSHOT
on:
  release:
    types:
      - published
permissions:
  contents: write # To write the version change to the repository
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Publish with Gradle
        run: ./gradlew :incrementVersion --no-daemon
      - name: Update version in gradle.properties
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add gradle.properties
          git commit -m "Update to next development version"
          git push --tags